app:
  module: translate
  gui: true

server:
  port: 0

ai:
  provider: ollama
  ollama:
    url: http://localhost:11434
    model: gemma2:2b
  openai:
    apiKey: ${OPENAI_API_KEY:}
    model: gpt-4o-mini
  gemini:
    apiKey: ${GEMINI_API_KEY:}
    model: gemini-1.5-flash
  googletranslate:
    apiKey: ${GOOGLE_TRANSLATE_API_KEY:}

io:
  inputDir: ./data/input
  outputDir: ./data/output
