package com.aiwrapper.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.Map;

public class TranslationFileSyncService {

    public void autoExportToGame(String gamePath, File activeCache) throws Exception {
        if (gamePath == null || gamePath.trim().isEmpty()) {
            return;
        }
        if (activeCache == null || !activeCache.exists()) {
            return;
        }
        File exe = new File(gamePath);
        File transFile = new File(exe.getParentFile(), "BepInEx/Translation/vi/Text/_AutoGeneratedTranslations.txt");

        ObjectMapper mapper = new ObjectMapper();
        Map<String, String> cacheMap = mapper.readValue(activeCache,
                new TypeReference<Map<String, String>>() {
                });
        if (cacheMap.isEmpty()) {
            return;
        }

        if (transFile.getParentFile() != null && !transFile.getParentFile().exists()) {
            transFile.getParentFile().mkdirs();
        }

        try (BufferedWriter writer = new BufferedWriter(
                new OutputStreamWriter(new FileOutputStream(transFile), StandardCharsets.UTF_8))) {
            writer.write("# Generated by AI Translation Tool\n");
            for (Map.Entry<String, String> entry : cacheMap.entrySet()) {
                writer.write(entry.getKey() + "=" + entry.getValue() + "\n");
            }
        }
    }
}
