package com.aiwrapper.javafx.ui;

import com.aiwrapper.executor.TranslateExecutor;
import javafx.collections.ObservableList;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import javafx.scene.control.Alert;
import javafx.scene.control.ButtonType;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.BufferedWriter;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.Optional;
import java.util.function.Supplier;

public class CacheImportExportHandler {

    public static void handleSync(
            Stage stage,
            TranslateExecutor translateExecutor,
            Supplier<String> gamePathSupplier,
            Runnable onRowChanged,
            Runnable onCacheFileChange,
            ObservableList<TranslationItem> historyList) {
        String path = (gamePathSupplier != null) ? gamePathSupplier.get() : "";
        if (path.isEmpty()) {
            Alert alert = new Alert(Alert.AlertType.WARNING, "Vui lòng chọn đường dẫn game Game Exe trước!");
            alert.showAndWait();
            return;
        }
        File exe = new File(path);
        File transFile = new File(exe.getParentFile(),
                "BepInEx/Translation/vi/Text/_AutoGeneratedTranslations.txt");

        File activeCache = translateExecutor.getActiveCacheFile();
        if (activeCache == null || !activeCache.exists()) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setHeaderText("No Active Cache");
            alert.setContentText("There is no active cache file loaded or found for this game.");
            File cssFile = new File("data/ui_style.css");
            if (cssFile.exists()) {
                alert.getDialogPane().getStylesheets().add(cssFile.toURI().toString());
            }
            alert.showAndWait();
            return;
        }

        try {
            com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();
            Map<String, String> cacheMap = mapper.readValue(activeCache,
                    new com.fasterxml.jackson.core.type.TypeReference<Map<String, String>>() {
                    });

            if (cacheMap.isEmpty()) {
                Alert alert = new Alert(Alert.AlertType.INFORMATION);
                alert.setTitle("Information");
                alert.setHeaderText("Active Cache Empty");
                alert.setContentText("The active JSON cache file is empty. Nothing to export.");
                File cssFile = new File("data/ui_style.css");
                if (cssFile.exists()) {
                    alert.getDialogPane().getStylesheets().add(cssFile.toURI().toString());
                }
                alert.showAndWait();
                return;
            }

            Alert confirm = new Alert(Alert.AlertType.CONFIRMATION);
            confirm.setTitle("Confirm Export");
            confirm.setHeaderText("Export Cache to Game");
            confirm.setContentText(
                    "This will write " + cacheMap.size() + " translations to BepInEx's translation file:\n"
                            + transFile.getAbsolutePath() + "\n\nDo you want to proceed?");
            File cssFile = new File("data/ui_style.css");
            if (cssFile.exists()) {
                confirm.getDialogPane().getStylesheets().add(cssFile.toURI().toString());
            }
            Optional<ButtonType> result = confirm.showAndWait();
            if (result.isPresent() && result.get() == ButtonType.OK) {
                if (transFile.getParentFile() != null && !transFile.getParentFile().exists()) {
                    transFile.getParentFile().mkdirs();
                }

                try (BufferedWriter writer = new BufferedWriter(
                        new OutputStreamWriter(new FileOutputStream(transFile),
                                StandardCharsets.UTF_8))) {
                    writer.write("# Generated by AI Translation Tool\n");
                    for (Map.Entry<String, String> entry : cacheMap.entrySet()) {
                        writer.write(entry.getKey() + "=" + entry.getValue() + "\n");
                    }
                }

                Alert successAlert = new Alert(Alert.AlertType.INFORMATION);
                successAlert.setTitle("Success");
                successAlert.setHeaderText("Export Complete");
                successAlert
                        .setContentText("Successfully exported " + cacheMap.size() + " translations to game file!");
                if (cssFile.exists()) {
                    successAlert.getDialogPane().getStylesheets().add(cssFile.toURI().toString());
                }
                successAlert.showAndWait();
            }
        } catch (Exception ex) {
            Alert errAlert = new Alert(Alert.AlertType.ERROR);
            errAlert.setTitle("Error");
            errAlert.setHeaderText("Export Failed");
            errAlert.setContentText("Failed to export to game:\n" + ex.getMessage());
            File cssFile = new File("data/ui_style.css");
            if (cssFile.exists()) {
                errAlert.getDialogPane().getStylesheets().add(cssFile.toURI().toString());
            }
            errAlert.showAndWait();
        }
    }

    public static void loadCache(
            Stage stage,
            TranslateExecutor translateExecutor,
            ObservableList<TranslationItem> historyList,
            Runnable updateLabelCallback,
            Runnable onCacheFileChange) {
        FileChooser chooser = new FileChooser();
        chooser.setTitle("Select Cache JSON File");
        chooser.setInitialDirectory(new File("data"));
        chooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("JSON (*.json)", "*.json"));
        File file = chooser.showOpenDialog(stage);
        if (file != null) {
            try {
                com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();
                Map<String, String> cMap = mapper.readValue(file,
                        new com.fasterxml.jackson.core.type.TypeReference<Map<String, String>>() {
                        });
                historyList.clear();
                for (Map.Entry<String, String> entry : cMap.entrySet()) {
                    historyList.add(new TranslationItem("Cache", entry.getKey(), entry.getValue()));
                }
                translateExecutor.setActiveCacheFile(file);
                if (updateLabelCallback != null) {
                    updateLabelCallback.run();
                }
                if (onCacheFileChange != null) {
                    onCacheFileChange.run();
                }
                System.out.println("Loaded " + cMap.size() + " translation mappings from cache: " + file.getName());
            } catch (Exception ex) {
                System.err.println("Failed to read cache file: " + ex.getMessage());
            }
        }
    }

    public static void clearCache(
            Stage stage,
            Supplier<String> gamePathSupplier,
            TranslateExecutor translateExecutor,
            ObservableList<TranslationItem> historyList,
            Runnable updateLabelCallback,
            Runnable onCacheFileWiped) {
        String path = (gamePathSupplier != null) ? gamePathSupplier.get() : "";
        if (path.isEmpty()) {
            Alert alert = new Alert(Alert.AlertType.WARNING);
            alert.setTitle("Warning");
            alert.setHeaderText("Game Executable Key Missing");
            alert.setContentText("Please select the Game Exe Path in the settings panel first.");
            File cssFile = new File("data/ui_style.css");
            if (cssFile.exists()) {
                alert.getDialogPane().getStylesheets().add(cssFile.toURI().toString());
            }
            alert.showAndWait();
            return;
        }

        Alert confirm = new Alert(Alert.AlertType.CONFIRMATION);
        confirm.setTitle("Confirm Deletion");
        confirm.setHeaderText("Clear cache files?");
        confirm.setContentText("Are you sure you want to delete the game cache and proxy cached translations?");
        File cssFile = new File("data/ui_style.css");
        if (cssFile.exists()) {
            confirm.getDialogPane().getStylesheets().add(cssFile.toURI().toString());
        }
        confirm.showAndWait().ifPresent(res -> {
            if (res == ButtonType.OK) {
                File exe = new File(path);
                String gameName = exe.getName();
                if (gameName.endsWith(".exe")) {
                    gameName = gameName.substring(0, gameName.length() - 4);
                }
                File gameCache = new File("data/cache_" + gameName + ".json");
                if (gameCache.exists()) {
                    gameCache.delete();
                }
                File targetCache = new File(exe.getParentFile(),
                        "BepInEx/Translation/vi/Text/_AutoGeneratedTranslations.txt");
                if (targetCache.exists()) {
                    targetCache.delete();
                }
                historyList.clear();
                translateExecutor.setActiveCacheFile(null);
                if (updateLabelCallback != null) {
                    updateLabelCallback.run();
                }
                if (onCacheFileWiped != null) {
                    onCacheFileWiped.run();
                }
                System.out.println("Caches wiped successfully.");
            }
        });
    }
}
